public interface IAuth
{
    // RETURNS A STRING REPRESENTING THE AUTHENTICATION TOKEN OR CREDENTIALS, OR NULL IF AUTHENTICATION IS NOT REQUIRED OR FAILED.
    // THE TIMESTAMP PARAMETER CAN BE USED TO PROVIDE A UNIQUE IDENTIFIER FOR THE AUTHENTICATION ATTEMPT, IF NEEDED.
    // THE ONPROGRESS CALLBACK CAN BE USED TO REPORT PROGRESS OR STATUS MESSAGES DURING THE AUTHENTICATION PROCESS, IF DESIRED.
    Task<string?> AuthenticateAsync(IConfig config, string timestamp, Action<string>? onProgress = null);
}
